In [2]:
import pandas as pd
import numpy as np
from google.colab import drive

In [3]:
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [8]:
df1 = pd.read_csv("gdrive/MyDrive/train_data.csv")
df2 = pd.read_csv("gdrive/MyDrive/evaluation_data.csv")
df = df1.append(df2, ignore_index = True)

In [9]:
df2

            id      timestamp  retweet_count  ...  positive  negative  text_size
0       665776  1588644489777            NaN  ...         0         0          6
1       665777  1588463988413            NaN  ...         0         0         20
2       665778  1588563932106            NaN  ...         0         0          5
3       665779  1588639210045            NaN  ...         1         0         32
4       665780  1588692867357            NaN  ...         1         1         53
...        ...            ...            ...  ...       ...       ...        ...
285329  951105  1588673869339            NaN  ...         0         0         44
285330  951106  1588296137844            NaN  ...         0         0         32
285331  951107  1588550324249            NaN  ...         0         0         46
285332  951108  1588656171612            NaN  ...         0         0          5
285333  951109  1588577717251            NaN  ...         0         0         22

[285334 rows x 37 columns]

In [10]:
df1 = pd.read_csv("gdrive/MyDrive/train.csv")
df2 = pd.read_csv("gdrive/MyDrive/evaluation.csv")
df_text = df1.append(df2, ignore_index = True)

In [11]:
df2

            id  ...                                               text
0       665776  ...  Coronavirus, no spring break, Chris Brown fan ...
1       665777  ...                                This fits the data.
2       665778  ...  Y’all talk about the Coronavirus like y’all be...
3       665779  ...  As this coronavirus and covid-19 go on, the fo...
4       665780  ...  Big Brother is not very good at watching you. ...
...        ...  ...                                                ...
285329  951105  ...  #IndianArmy fights COVID-19\n\n#HarKaamDeshKeN...
285330  951106  ...  (04/22/2020) “CUT-THE-RONA” \n\nWe would like ...
285331  951107  ...                                It's just starting.
285332  951108  ...  It is in no way a surprise that one of the fou...
285333  951109  ...            Very impressive https://t.co/xVAdPYh8IT

[285334 rows x 10 columns]

In [12]:
df["text"] = df_text["text"]

In [13]:
df.nlargest(100, ["retweet_count"])

            id  ...                                               text
546442  546442  ...                Never Not 💜 https://t.co/Ag9oUTJvrN
565532  565532  ...  To all the little girls watching...never doubt...
225845  225845  ...                          ☺ https://t.co/9vNeJtA1vW
117825  117825  ...  Easily one of the best social distancing ads I...
622524  622524  ...  I can’t believe I have to say this, but please...
...        ...  ...                                                ...
448498  448498  ...  This is exactly how females are lmfaoooo https...
34401    34401  ...  We can now read the Imperial College report on...
636765  636765  ...  how tf am I an essential worker https://t.co/3...
651667  651667  ...  Very American to decide we are bored with COVI...
484978  484978  ...  If my husband cut like this without trying to ...

[100 rows x 38 columns]

In [14]:
df[((df["user_statuses_count"] >= 12000) & (df["user_statuses_count"] <= 13000) &
    (df["user_friends_count"] >= 125) & (df["user_friends_count"] <= 145)
    & (df["user_followers_count"] >= 2000000))]

            id  ...                                               text
7357      7357  ...  염색 했을 때 촬칵 !! \n우리 아미 머해요옹??\n\n #BOTD #BTS_OF...
143257  143257  ...  가족들과 소중한 시간들이 되길 바랄게요😊\n#JIMIN https://t.co/PV...
225845  225845  ...                          ☺ https://t.co/9vNeJtA1vW
546442  546442  ...                Never Not 💜 https://t.co/Ag9oUTJvrN
877921  877920  ...  어버이날 카네이션은 역시 어린이날에 만들어야! https://t.co/rbWKmL3e9H

[5 rows x 38 columns]

In [15]:
df.loc[:, "user"] = '0'

In [16]:
df.loc[((df["user_statuses_count"] >= 12000) & (df["user_statuses_count"] <= 13000) &
    (df["user_friends_count"] >= 125) & (df["user_friends_count"] <= 145)
    & (df["user_followers_count"] >= 2000000)), "user"] = 'BTS'

In [18]:
df.nlargest(15, ["retweet_count"]).loc[df.nlargest(15, ["retweet_count"])["user"] == '0']

            id  ...  user
565532  565532  ...     0
117825  117825  ...     0
622524  622524  ...     0
384422  384422  ...     0
556993  556993  ...     0
211555  211555  ...     0
275029  275029  ...     0
360433  360433  ...     0
67926    67926  ...     0
416321  416321  ...     0
419323  419323  ...     0

[11 rows x 39 columns]

In [19]:
df[((df["user_statuses_count"] >= 10000) & (df["user_statuses_count"] <= 20000) &
    (df["user_friends_count"] >= 600) & (df["user_friends_count"] <= 1000)
    & (df["user_followers_count"] >= 27000000) )]

            id  ...  user
30575    30575  ...     0
106771  106771  ...     0
168972  168972  ...     0
214166  214166  ...     0
231204  231204  ...     0
252916  252916  ...     0
271654  271654  ...     0
315337  315337  ...     0
320928  320928  ...     0
333494  333494  ...     0
436197  436197  ...     0
446713  446713  ...     0
531115  531115  ...     0
549662  549662  ...     0
565532  565532  ...     0
565655  565655  ...     0
583463  583463  ...     0
584994  584994  ...     0
591761  591761  ...     0
663396  663396  ...     0
692694  692693  ...     0
700538  700537  ...     0
714188  714187  ...     0
833629  833628  ...     0
860494  860493  ...     0
922184  922183  ...     0
923675  923674  ...     0

[27 rows x 39 columns]

In [20]:
df.loc[((df["user_statuses_count"] >= 10000) & (df["user_statuses_count"] <= 20000) &
    (df["user_friends_count"] >= 600) & (df["user_friends_count"] <= 1000)
    & (df["user_followers_count"] >= 27000000) ), "user"] = 'Hilary'

In [21]:
#pd.set_option("display.max_rows", None, "display.max_columns", None)
df.nlargest(15, ["retweet_count"]).loc[df.nlargest(15, ["retweet_count"])["user"] == '0']

            id  ...  user
117825  117825  ...     0
622524  622524  ...     0
384422  384422  ...     0
556993  556993  ...     0
211555  211555  ...     0
275029  275029  ...     0
360433  360433  ...     0
67926    67926  ...     0
416321  416321  ...     0
419323  419323  ...     0

[10 rows x 39 columns]

In [56]:
df.loc[((df["user_statuses_count"] >= 1800) & (df["user_statuses_count"] <= 2100) &
    (df["user_friends_count"] >= 1400) & (df["user_friends_count"] <= 1550)
    & (df["user_followers_count"] >= 14000) )]

,id,timestamp,retweet_count,user_verified,user_statuses_count,user_followers_count,user_friends_count,user_mentions,urls,hashtags,date,hour,day,month,weekday,weekend,friends_followers_ratio,has_hashtags,has_mentions,has_urls,number_of_urls,number_of_mentions,number_of_hashtags,urls_popularity,hashtags_popularity,mentions_popularity,mentions_max_followers,mentions_max_friends,fear,anger,joy,disgust,sadness,surprise,positive,negative,text_size,text,user
87524,87524,1588293605676,33.0,0,2027,16524,1469,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 00:40:05,0,1,5,4,0,0.088901,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,30,And former U.S. Secretary of State Madeleine A...,0
117825,117825,1588305672852,415787.0,0,1956,14783,1530,NaN,NaN,NaN,2020-05-01 04:01:12,4,1,5,4,0,0.103497,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,15,Easily one of the best social distancing ads I...,0
230133,230133,1588579766499,39.0,0,1965,14166,1518,manygaythings,twitter.com/i/web/status/1…,"RawIsLaw, Breeding",2020-05-04 08:09:26,8,4,5,0,0,0.107158,1,1,1,1,1,2,242936,NaN,0,0.0,0.0,0,0,0,0,0,0,0,0,26,Pre-coronavirus fun: White caged sub @manygayt...,0
239968,239968,1588315589397,2.0,0,2027,16526,1469,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 06:46:29,6,1,5,4,0,0.088890,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,40,Journalist Michael Specter has reported on Ant...,0
310977,310977,1588353693708,7.0,0,2027,16528,1476,Sulliview,twitter.com/i/web/status/1…,NaN,2020-05-01 17:21:33,17,1,5,4,0,0.089303,0,1,1,1,1,0,242936,0.0,1,0.0,0.0,0,0,0,0,0,1,1,0,31,How should the media cover President Trump and...,0
351119,351119,1588501959971,17.0,0,2014,21065,1459,NaN,twitter.com/paulodonoghue9…,NaN,2020-05-03 10:32:39,10,3,5,6,1,0.069262,0,0,1,1,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,26,What’s the point in protecting insurance compa...,0
364548,364548,1588315778568,5.0,0,2027,16526,1469,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 06:49:38,6,1,5,4,0,0.088890,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,35,When will sports fans be able to return to the...,0
500793,500793,1588673788124,3.0,0,2067,122887,1509,LeeChildReacher,twitter.com/i/web/status/1…,NaN,2020-05-05 10:16:28,10,5,5,1,0,0.012280,0,1,1,1,1,0,242936,0.0,0,0.0,0.0,0,0,0,0,0,0,2,0,50,"So grateful to the master, @LeeChildReacher, f...",0
562572,562572,1588315724447,5.0,0,2027,16526,1469,"camanpour, lawrence_wright",twitter.com/i/web/status/1…,NaN,2020-05-01 06:48:44,6,1,5,4,0,0.088890,0,1,1,1,2,0,242936,0.0,1,0.0,0.0,0,0,0,0,0,0,0,0,24,Did this novel predict the COVID-19 pandemic? ...,0
562675,562675,1588315730127,3.0,0,2027,16526,1469,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 06:48:50,6,1,5,4,0,0.088890,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,1,1,0,27,Former U.S. Senate Majority Leader Bill Frist ...,0
574135,574135,1588545476085,0.0,1,1831,20042,1437,NaN,NaN,NaN,2020-05-03 22:37:56,22,3,5,6,1,0.071699,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,12,God bless the mental health professionals righ...,0
614133,614133,1588315734478,2.0,0,2027,16526,1469,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 06:48:54,6,1,5,4,0,0.088890,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,28,"And finally, actor Kevin Bacon explains how he...",0
629474,629474,1588679582956,4.0,0,2085,18735,1533,NaN,twitter.com/i/web/status/1…,COVID19,2020-05-05 11:53:02,11,5,5,1,0,0.081825,1,0,1,1,0,1,242936,25490.0,0,NaN,NaN,0,0,0,0,0,0,3,0,34,ASHRAE’s in the News! Listen to members from A...,0
631762,631762,1588608265385,45.0,0,2035,16551,1479,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 16:04:25,16,4,5,0,0,0.089360,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,1,30,Dr. Richard Levitan explains what we can learn...,0
693217,693216,1588633594813,NaN,0,2039,16550,1480,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 23:06:34,23,4,5,0,0,0.089426,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,7,The reason why this virus is honestly so scary...,0
733159,733158,1588315584187,NaN,0,2027,16526,1469,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 06:46:24,6,1,5,4,0,0.088890,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,24,"Plus, the president of Americans for Prosperit...",0
739776,739775,1588358792128,NaN,0,1973,14783,1531,NaN,NaN,NaN,2020-05-01 18:46:32,18,1,5,4,0,0.103565,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,4,"On the one hand, this is the right thing to do...",0
758996,758995,1588678253998,NaN,0,2039,16566,1480,"MichelMcQMartin, cduhigg",twitter.com/i/web/status/1…,NaN,2020-05-05 11:30:53,11,5,5,1,0,0.089340,0,1,1,1,2,0,242936,0.0,0,0.0,0.0,0,0,0,0,0,0,0,1,16,"Plus, journalist Charles Duhigg compares the p...",0
777560,777559,1588450341555,NaN,1,1844,20495,1404,NaN,twitter.com/i/web/status/1…,NaN,2020-05-02 20:12:21,20,2,5,5,1,0.068505,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,1,0,0,1,1,7,Pleased to participate and pledge Canada’s 🇨🇦 ...,0
813097,813096,1588315768388,NaN,0,2027,16526,1469,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 06:49:28,6,1,5,4,0,0.088890,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,2,0,26,"And finally, mathematician and geneticist Eric...",0
820883,820882,1588314097324,NaN,0,2024,16072,1475,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 06:21:37,6,1,5,4,0,0.091775,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,5,14th April\nUK GOV: 'You do not and should not...,0
837251,837250,1588529282891,NaN,0,2035,16550,1479,"hari, airwaycam, camanpour",twitter.com/i/web/status/1…,NaN,2020-05-03 18:08:02,18,3,5,6,1,0.089366,0,1,1,1,3,0,242936,0.0,1,0.0,1513.0,0,0,0,0,0,0,0,0,5,Dr. Richard Levitan explains why COVID-19 pati...,0
875688,875687,1588315784735,NaN,0,2027,16526,1469,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 06:49:44,6,1,5,4,0,0.088890,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,7,"Before society can reopen, we need to reduce R...",0
898151,898150,1588457946688,NaN,0,1975,29913,1509,NaN,twitter.com/i/web/status/1…,NaN,2020-05-02 22:19:06,22,2,5,5,1,0.050446,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,9,Here’s a helpful breakdown of the typical proc...,0
940942,940941,1588315754927,NaN,0,2027,16526,1469,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 06:49:14,6,1,5,4,0,0.088890,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,25,Pulitzer Prize-winners David Rohde and Anne Ap...,0
942496,942495,1588458912453,NaN,0,1814,14068,1491,NaN,twitter.com/i/web/status/1…,"coronapocolypse, StayTheFHome, coronavirus",2020-05-02 22:35:12,22,2,5,5,1,0.105985,1,0,1,1,0,3,242936,4700.0,0,NaN,NaN,0,0,0,0,0,0,2,0,17,Please stay home. Wash your hands. Practice gr...,0

In [57]:
df.loc[((df["user_statuses_count"] >= 1800) & (df["user_statuses_count"] <= 2100) & (df["user_friends_count"] ==1530)
    & (df["user_followers_count"] >= 14000) ), "user"] = 'Unique_user_1'

In [58]:
df.nlargest(100, ["retweet_count"]).loc[df.nlargest(100, ["retweet_count"])["user"] == '0']

,id,timestamp,retweet_count,user_verified,user_statuses_count,user_followers_count,user_friends_count,user_mentions,urls,hashtags,date,hour,day,month,weekday,weekend,friends_followers_ratio,has_hashtags,has_mentions,has_urls,number_of_urls,number_of_mentions,number_of_hashtags,urls_popularity,hashtags_popularity,mentions_popularity,mentions_max_followers,mentions_max_friends,fear,anger,joy,disgust,sadness,surprise,positive,negative,text_size,text,user
622524,622524,1588611150023,334427.0,1,4622,5313436,26,NaN,NaN,NaN,2020-05-04 16:52:30,16,4,5,0,0,0.000005,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,19,"I can’t believe I have to say this, but please...",0
384422,384422,1588647768395,333211.0,0,162,22198,15,NaN,NaN,NaN,2020-05-05 03:02:48,3,5,5,1,0,0.000676,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,4,this is fucking bullshit,0
556993,556993,1588544598803,252369.0,0,778,19125,84,NaN,twitter.com/i/web/status/1…,NaN,2020-05-03 22:23:18,22,3,5,6,1,0.004392,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,53,"While humans carry out social distancing, a gr...",0
211555,211555,1588653470385,241820.0,1,6947,160763,813,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 04:37:50,4,5,5,1,0,0.005057,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,0,0,1,0,37,Holy shit. Katie Porter holds the CDC Director...,0
275029,275029,1588676325397,235681.0,0,14871,645,109,NaN,NaN,NaN,2020-05-05 10:58:45,10,5,5,1,0,0.168992,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,6,covid-19 please stop your world tour,0
360433,360433,1588670638696,223983.0,1,63000,17298,4402,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 09:23:58,9,5,5,1,0,0.254480,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,35,"oh my god, the chicago aquarium closed due to ...",0
67926,67926,1588672910115,209370.0,0,43314,82964,275,NaN,NaN,"COVID19, CoronavirusPandemic",2020-05-05 10:01:50,10,5,5,1,0,0.003315,1,0,0,0,0,2,0,25490.0,0,NaN,NaN,0,0,0,0,0,0,0,0,16,Sicily has figured out this whole self-isolati...,0
416321,416321,1588653801086,208844.0,0,114324,1536,408,NaN,NaN,NaN,2020-05-05 04:43:21,4,5,5,1,0,0.265625,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,15,the government be like: due to the coronavirus...,0
419323,419323,1588711235137,208130.0,0,1091,2487,286,NaN,NaN,NaN,2020-05-05 20:40:35,20,5,5,1,0,0.114998,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,11,COVID-19 helping people realise that some meet...,0
288191,288191,1588678495826,207384.0,0,229097,4344,882,NaN,NaN,NaN,2020-05-05 11:34:55,11,5,5,1,0,0.203039,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,18,Not enough praise has gone to medical professi...,0
618560,618560,1588659206678,204522.0,0,9987,9837,428,NaN,NaN,NaN,2020-05-05 06:13:26,6,5,5,1,0,0.043509,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,10,Coronavirus has crossed the line for Italians ...,0
153971,153971,1588655712228,194810.0,1,278,62754,298,MelBrooks,NaN,"coronavirus, DontBeASpreader",2020-05-05 05:15:12,5,5,5,1,0,0.004749,1,1,0,0,1,2,0,7706.0,0,0.0,0.0,0,0,0,0,0,0,0,0,18,"A message from me and my dad, @Melbrooks. \n\n...",0
197725,197725,1588679567664,187101.0,0,9436,4880,848,NaN,NaN,NaN,2020-05-05 11:52:47,11,5,5,1,0,0.173770,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,29,For the average American the best way to tell ...,0
61201,61201,1588690552467,186897.0,0,22779,681,324,NaN,NaN,NaN,2020-05-05 14:55:52,14,5,5,1,0,0.475771,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,17,My mans House would pop 6 Vicodin on Thursday ...,0
408817,408817,1588663290885,185406.0,0,86803,1238,99,NaN,NaN,NaN,2020-05-05 07:21:30,7,5,5,1,0,0.079968,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,15,when the coronavirus tweets are funny but ur s...,0
470317,470317,1588700599996,178111.0,0,876,5361,4292,NaN,NaN,NaN,2020-05-05 17:43:19,17,5,5,1,0,0.800597,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,20,My dog after I sent him to get supplies since ...,0
535135,535135,1588647965163,168249.0,1,142957,138422,11082,NaN,NaN,NaN,2020-05-05 03:06:05,3,5,5,1,0,0.080060,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,2,0,26,In retrospect Sandy Hook marked the end of the...,0
469058,469058,1588630157117,166665.0,1,15794,117029367,606826,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 22:09:17,22,4,5,0,0,0.005185,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,1,0,0,0,2,1,59,If you’re wondering whether it’s an overreacti...,0
210249,210249,1588615454048,163910.0,0,21633,18035,2849,NaN,NaN,NaN,2020-05-04 18:04:14,18,4,5,0,0,0.157971,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,23,This poor man is going to die tryna save Ameri...,0
277334,277334,1588566245397,160631.0,0,14078,357,225,NaN,NaN,NaN,2020-05-04 04:24:05,4,4,5,0,0,0.630252,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,5,The coronavirus canceling my plans,0
224651,224651,1588698802271,160229.0,0,23928,711,201,NaN,NaN,NaN,2020-05-05 17:13:22,17,5,5,1,0,0.282700,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,17,Me sending my dog out for supplies since he ca...,0
471393,471393,1588682482427,159168.0,0,37875,48801,35254,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 12:41:22,12,5,5,1,0,0.722403,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,27,900 people get Coronavirus and the whole world...,0
340499,340499,1588683476491,156817.0,1,25238,118691,1860,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 12:57:56,12,5,5,1,0,0.015671,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,60,So society’s *real* key workers have just bee...,0
327965,327965,1588709078019,155376.0,1,15802,39492,228,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 20:04:38,20,5,5,1,0,0.005773,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,2,0,57,I see a lot of people being like “I would surv...,0
60577,60577,1588662916620,153743.0,0,13419,1251,762,NaN,NaN,NaN,2020-05-05 07:15:16,7,5,5,1,0,0.609113,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,11,No offense but the corona virus disappearing b...,0
119322,119322,1588648970140,146077.0,0,2548,4109,435,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 03:22:50,3,5,5,1,0,0.105865,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,1,0,0,61,key takeaway: humans aren’t the problem—it’s o...,0
566837,566837,1588677191804,145836.0,1,1243,453844,102,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 11:13:11,11,5,5,1,0,0.000225,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,1,2,1,58,I did the math: a full battery of coronavirus ...,0
495234,495234,1588693071066,144887.0,0,40,32692,0,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 15:37:51,15,5,5,1,0,0.000000,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,14,😀😀😀😀😀😀😀😀😀😀 😀😀😀😀😀😀😀😀😀😀 😀😀😀😀😀😀😀😀pain😀😀 😀😀😀😀😀😀😀😀😀...,0
638579,638579,1588648642050,144605.0,0,328955,2286,1328,NaN,NaN,NaN,2020-05-05 03:17:22,3,5,5,1,0,0.580927,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,6,This is HARD AS FUCK.,0
280864,280864,1588607509243,141000.0,0,800,227,99,NaN,NaN,NaN,2020-05-04 15:51:49,15,4,5,0,0,0.436123,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,13,Imagine you want to sleep at night but your ne...,0
605256,605256,1588573440305,140896.0,0,18364,13605,766,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 06:24:00,6,4,5,0,0,0.056303,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,1,0,1,1,38,fun fact: its tradition for europeans to sprea...,0
430033,430033,1588715000662,138668.0,1,36629,238608,2516,NaN,NaN,NaN,2020-05-05 21:43:20,21,5,5,1,0,0.010544,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,6,How to medical https://t.co/0EDqJcy38p,0
157462,157462,1588321774642,138475.0,0,23905,1086,804,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 08:29:34,8,1,5,4,0,0.740331,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,26,Really don't wanna fucking hear about how hard...,0
60523,60523,1588658214548,138127.0,1,5548,34333517,1953,NaN,NaN,NaN,2020-05-05 05:56:54,5,5,5,1,0,0.000057,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,6,I had gloves on all day..,0
35507,35507,1588333516887,136876.0,0,102923,5444,1484,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 11:45:16,11,1,5,4,0,0.272594,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,1,1,1,1,53,Coronavirus is everywhere. BOOK THAT FLIGHT. T...,0
334253,334253,1588666513951,136665.0,0,4771,440,472,NaN,NaN,NaN,2020-05-05 08:15:13,8,5,5,1,0,1.072727,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,14,"First the coronavirus, \nand now this??\nJesus...",0
331773,331773,1588603693636,133198.0,1,67047,146318,5310,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 14:48:13,14,4,5,0,0,0.036291,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,1,1,0,0,0,2,1,59,If ONE white woman accused me of rape my caree...,0
596182,596182,1588691490352,131810.0,0,841,1851,545,NaN,NaN,NaN,2020-05-05 15:11:30,15,5,5,1,0,0.294435,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,12,So my possum living in the grill had babies ht...,0
459603,459603,1588510433609,131089.0,0,5881,179797,653,NaN,twitter.com/i/web/status/1…,NaN,2020-05-03 12:53:53,12,3,5,6,1,0.003632,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,32,After noticing that Ken slept with a photo of ...,0
465299,465299,1588555957161,131037.0,1,36762,207617,1958,NaN,NaN,NaN,2020-05-04 01:32:37,1,4,5,0,0,0.009431,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,25,Some dude just called me a pussy for putting o...,0
417192,417192,1588701971468,130964.0,1,15795,117057995,606799,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 18:06:11,18,5,5,1,0,0.005184,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,4,0,55,Protect yourself and your community from coron...,0
50242,50242,1588673332425,129528.0,0,22756,25900,3978,NaN,NaN,NaN,2020-05-05 10:08:52,10,5,5,1,0,0.153591,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,8,Coronavirus said this ones for you Princess Diana,0
401441,401441,1588651774289,128469.0,0,5787,3069,267,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 04:09:34,4,5,5,1,0,0.086999,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,60,Yesterday I knocked on my Tennant's door and t...,0
321606,321606,1588702466133,128138.0,0,51319,1313,2095,NaN,NaN,NaN,2020-05-05 18:14:26,18,5,5,1,0,1.595583,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,12,Hockey has been cancelled for like six hours a...,0
592212,592212,1588299085941,126414.0,0,111663,27127,1334,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 02:11:25,2,1,5,4,0,0.049176,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,2,53,This is the face of someone who just spent 9 h...,0
486991,486991,1588594181612,126026.0,0,6083,591,1005,NaN,NaN,NaN,2020-05-04 12:09:41,12,4,5,0,0,1.700508,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,10,If you believe the world will overcome covid-1...,0
290272,290272,1588557287222,124257.0,1,7081,4589670,808,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 01:54:47,1,4,5,0,0,0.000176,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,69,stop scrolling 🛑 ✋🏾!!! IM FROM THE FUTURE 🤖 🚀🚨...,0
477458,477458,1588681771016,123334.0,1,17932,11918035,1460,NaN,NaN,NaN,2020-05-05 12:29:31,12,5,5,1,0,0.000123,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,13,"Once a vaccine for coronavirus is developed, i...",0
5750,5750,1588665075225,122475.0,0,49182,2149,1635,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 07:51:15,7,5,5,1,0,0.760819,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,43,Can y’all please just follow the government in...,0
568007,568007,1588648779854,122382.0,0,1196,8645,122,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 03:19:39,3,5,5,1,0,0.014112,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,1,0,0,1,54,"I live in Seattle, I have all symptoms of COVI...",0
231642,231642,1588683849841,121405.0,0,65595,6488,634,NaN,NaN,NaN,2020-05-05 13:04:09,13,5,5,1,0,0.097719,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,7,Damn I gotta warn my mum,0
30557,30557,1588640100811,120903.0,0,35482,21398,762,NaN,NaN,NaN,2020-05-05 00:55:00,0,5,5,1,0,0.035611,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,13,coronavirus seeing all the other terrible shit...,0
535541,535541,1588628223199,120632.0,0,102343,2912,1509,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 21:37:03,21,4,5,0,0,0.518201,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,3,0,53,"After COVID-19 is over, I better NEVER hear an...",0
86760,86760,1588584268047,119447.0,0,81119,80412,34025,NaN,NaN,NaN,2020-05-04 09:24:28,9,4,5,0,0,0.423133,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,8,the coronavirus outbreak in Italy https://t.co...,0
436384,436384,1588701292780,118635.0,0,8618,4317,2163,NaN,NaN,NaN,2020-05-05 17:54:52,17,5,5,1,0,0.501042,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,10,Me and my best friend reuniting once coronavir...,0
579912,579912,1588305576565,118362.0,0,4096,19690,7380,NaN,NaN,NaN,2020-05-01 03:59:36,3,1,5,4,0,0.374810,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,14,i can't believe school used to start at 8am an...,0
492090,492090,1588576328356,117236.0,1,8009,80112,1001,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 07:12:08,7,4,5,0,0,0.012495,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,0,0,0,0,48,Italy has banned weddings and funerals for 16 ...,0
602427,602427,1588553259700,116628.0,0,48822,123612,804,NaN,NaN,NaN,2020-05-04 00:47:39,0,4,5,0,0,0.006504,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,12,This is the most Florida tweet I’ve ever seen.,0
191288,191288,1588566767120,116205.0,0,169384,3240,2916,NaN,NaN,NaN,2020-05-04 04:32:47,4,4,5,0,0,0.900000,0,0,0,0,0,0,0,0.0,0,NaN,NaN,1,0,0,0,0,0,0,1,15,“Avoid being in large masses of people to avoi...,0
596549,596549,1588668294650,115846.0,1,14318,454065,27,NaN,NaN,NaN,2020-05-05 08:44:54,8,5,5,1,0,0.000059,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,15,Coronavirus will end soon. In Jesus name. \n\n...,0
485026,485026,1588681705194,114634.0,0,133012,2530,1509,NaN,NaN,NaN,2020-05-05 12:28:25,12,5,5,1,0,0.596443,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,14,LMFAOO They jogging out that bitch like it’s a...,0
228400,228400,1588701470809,112474.0,1,944,100236,5029,NaN,NaN,NaN,2020-05-05 17:57:50,17,5,5,1,0,0.050172,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,27,"A Saudi doctor returns home from the hospital,...",0
498713,498713,1588520325180,108967.0,0,53001,2378,1482,NaN,NaN,NaN,2020-05-03 15:38:45,15,3,5,6,1,0.623213,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,8,Meredith Grey. Ugh this woman is amazing,0
394091,394091,1588650987302,108524.0,0,4397,560,528,NaN,NaN,NaN,2020-05-05 03:56:27,3,5,5,1,0,0.942857,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,16,coronavirus this coronavirus that.... can we t...,0
441362,441362,1588631518294,108010.0,0,16969,2723,541,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 22:31:58,22,4,5,0,0,0.198678,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,2,0,61,"For those of you who don’t know, Cuba’s larges...",0
31017,31017,1588571865928,107476.0,0,39591,9601,798,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 05:57:45,5,4,5,0,0,0.083116,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,0,0,0,0,45,The media: “CORONAVIRUS PANDEMIC IS GETTING WO...,0
503392,503392,1588662061470,106792.0,0,17402,2757,430,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 07:01:01,7,5,5,1,0,0.155967,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,56,seeing alot of people (esp influencers) shamin...,0
86180,86180,1588679783443,105762.0,0,1337,685,133,NaN,NaN,NaN,2020-05-05 11:56:23,11,5,5,1,0,0.194161,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,20,BREAKING NEWS: Due to the recent COVID-19 outb...,0
252655,252655,1588320236485,105598.0,0,755,1880754,0,NaN,NaN,NaN,2020-05-01 08:03:56,8,1,5,4,0,0.000000,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,3,https://t.co/WxJFzvHja4,0
637425,637425,1588631281698,104808.0,0,22519,96401,7650,NaN,NaN,NaN,2020-05-04 22:28:01,22,4,5,0,0,0.079356,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,11,Listen what this doctor said about coronavirus...,0
660972,660972,1588683772420,104696.0,0,16397,31574,1550,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 13:02:52,13,5,5,1,0,0.049091,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,1,0,0,50,This is Generation Z. \n\nI want to name that ...,0
556503,556503,1588635631722,104415.0,0,27752,5911,1841,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 23:40:31,23,4,5,0,0,0.311453,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,0,0,1,0,33,Quote of the year: “If you expect elementary s...,0
497681,497681,1588680268785,104005.0,1,80332,695875,12340,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 12:04:28,12,5,5,1,0,0.017733,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,32,Sandra the orangutang started washing her hand...,0
561557,561557,1588651601322,103708.0,1,8497,3046999,1051,TeamPulte,twitter.com/i/web/status/1…,NaN,2020-05-05 04:06:41,4,5,5,1,0,0.000345,0,1,1,1,1,0,242936,0.0,2,0.0,0.0,0,0,0,0,0,0,0,0,36,I'm going give $300 TODAY to someone random wh...,0
428949,428949,1588288237192,103062.0,1,9503,29142493,126,NaN,NaN,NaN,2020-04-30 23:10:37,23,30,4,3,0,0.000004,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,16,they act like i’m not in full control of where...,0
303209,303209,1588467545279,102674.0,0,1144,2392,222,NaN,twitter.com/i/web/status/1…,NaN,2020-05-03 00:59:05,0,3,5,6,1,0.092809,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,38,"Two nurses, who have witnessed first hand the ...",0
115891,115891,1588678639723,102239.0,0,11738,7661,982,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 11:37:19,11,5,5,1,0,0.128182,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,44,"Husband just told me, “watching the federal go...",0
313705,313705,1588547912685,102037.0,1,17855,444446,5933,NaN,twitter.com/i/web/status/1…,NaN,2020-05-03 23:18:32,23,3,5,6,1,0.013349,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,1,0,0,0,3,58,The H1N1 swine flu pandemic that infected up t...,0
228319,228319,1588555533327,101952.0,0,3190,611,712,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 01:25:33,1,4,5,0,0,1.165303,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,56,The Office: Coronavirus \n\nMichael ignores th...,0
45699,45699,1588480220630,100657.0,0,12380,4757,1074,NaN,NaN,NaN,2020-05-03 04:30:20,4,3,5,6,1,0.225773,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,12,niggas saw that hockey could get canceled and ...,0
91091,91091,1588649957007,100614.0,0,3224,7311,274,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 03:39:17,3,5,5,1,0,0.037478,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,0,0,0,2,68,"So, the last week I have been battling COVID-1...",0
42435,42435,1588689962719,98677.0,0,2404,485,181,NaN,NaN,NaN,2020-05-05 14:46:02,14,5,5,1,0,0.373196,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,14,why coronavirus gotta hit right when i started...,0
638407,638407,1588652589920,98517.0,0,12156,872,525,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 04:23:09,4,5,5,1,0,0.602064,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,26,2004- SARS \n2008- AVIAN \n2010- SWINE \n2014-...,0
54282,54282,1588689993810,97955.0,1,3308,50298361,218,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 14:46:33,14,5,5,1,0,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,50,Halting funding for the World Health Organizat...,0
494987,494987,1588636177403,97924.0,0,52567,46512,10339,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 23:49:37,23,4,5,0,0,0.222287,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,37,"Hi. \n\nYes, it originated in China, but the t...",0
419270,419270,1588573961668,97666.0,0,25581,9679,1595,NaN,NaN,NaN,2020-05-04 06:32:41,6,4,5,0,0,0.164790,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,16,Celebrities keep trying to sing the virus away...,0
406543,406543,1588685303449,97572.0,1,9466,206476,3721,NaN,twitter.com/i/web/status/1…,Coronavirus,2020-05-05 13:28:23,13,5,5,1,0,0.018021,1,0,1,1,0,1,242936,2740.0,0,NaN,NaN,0,0,0,0,0,0,0,0,32,This morning a White House official referred t...,0
404946,404946,1588614765260,97558.0,0,4504,90437,639,NaN,twitter.com/Corona_Bot__/s…,NaN,2020-05-04 17:52:45,17,4,5,0,0,0.007066,0,0,1,1,0,0,4,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,4,WHAT https://t.co/1Qq5x38onc,0
319293,319293,1588609427860,96922.0,1,6813,27868,520,NaN,NaN,NaN,2020-05-04 16:23:47,16,4,5,0,0,0.018659,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,8,Every Friday at exactly 7:30pm https://t.co/71...,0
448498,448498,1588567832167,96409.0,0,210088,43566,35151,NaN,NaN,NaN,2020-05-04 04:50:32,4,4,5,0,0,0.806845,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,10,This is exactly how females are lmfaoooo https...,0

In [24]:
df.loc[((df["user_statuses_count"] >= 3000) & (df["user_statuses_count"] <= 8000) &
    (df["user_friends_count"] == 26)
    & (df["user_followers_count"] >= 5000000) & (df["user_followers_count"] <= 6000000) )]

            id  ...   user
2094      2094  ...  Biden
12819    12819  ...  Biden
20682    20682  ...  Biden
36605    36605  ...  Biden
47156    47156  ...  Biden
...        ...  ...    ...
913027  913026  ...  Biden
917775  917774  ...  Biden
923502  923501  ...  Biden
934645  934644  ...  Biden
950984  950983  ...  Biden

[83 rows x 39 columns]

In [22]:
df.loc[((df["user_statuses_count"] >= 3000) & (df["user_statuses_count"] <= 8000) &
    (df["user_friends_count"] == 26)
    & (df["user_followers_count"] >= 5000000) & (df["user_followers_count"] <= 6000000) ), "user"] = 'Biden'

In [23]:
df.nlargest(30, ["retweet_count"]).loc[df.nlargest(30, ["retweet_count"])["user"] == '0']

            id  ...  user
117825  117825  ...     0
384422  384422  ...     0
556993  556993  ...     0
211555  211555  ...     0
275029  275029  ...     0
360433  360433  ...     0
67926    67926  ...     0
416321  416321  ...     0
419323  419323  ...     0
288191  288191  ...     0
618560  618560  ...     0
153971  153971  ...     0
197725  197725  ...     0
61201    61201  ...     0
408817  408817  ...     0
470317  470317  ...     0
535135  535135  ...     0
469058  469058  ...     0
210249  210249  ...     0
277334  277334  ...     0
224651  224651  ...     0
471393  471393  ...     0
340499  340499  ...     0
327965  327965  ...     0

[24 rows x 39 columns]

In [72]:
df.loc[((df["user_statuses_count"] >= 150) & (df["user_statuses_count"] <= 170) &
    (df["user_friends_count"] >= 10) & (df["user_friends_count"] <= 15)
    & (df["user_followers_count"] >= 20000) & (df["user_followers_count"] <= 30000), "user" )] = "user_4th_pop_tweet"

In [73]:
df.nlargest(100, ["retweet_count"]).loc[df.nlargest(100, ["retweet_count"])["user"] == '0']

,id,timestamp,retweet_count,user_verified,user_statuses_count,user_followers_count,user_friends_count,user_mentions,urls,hashtags,date,hour,day,month,weekday,weekend,friends_followers_ratio,has_hashtags,has_mentions,has_urls,number_of_urls,number_of_mentions,number_of_hashtags,urls_popularity,hashtags_popularity,mentions_popularity,mentions_max_followers,mentions_max_friends,fear,anger,joy,disgust,sadness,surprise,positive,negative,text_size,text,user
556993,556993,1588544598803,252369.0,0,778,19125,84,NaN,twitter.com/i/web/status/1…,NaN,2020-05-03 22:23:18,22,3,5,6,1,0.004392,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,53,"While humans carry out social distancing, a gr...",0
211555,211555,1588653470385,241820.0,1,6947,160763,813,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 04:37:50,4,5,5,1,0,0.005057,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,0,0,1,0,37,Holy shit. Katie Porter holds the CDC Director...,0
275029,275029,1588676325397,235681.0,0,14871,645,109,NaN,NaN,NaN,2020-05-05 10:58:45,10,5,5,1,0,0.168992,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,6,covid-19 please stop your world tour,0
360433,360433,1588670638696,223983.0,1,63000,17298,4402,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 09:23:58,9,5,5,1,0,0.254480,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,35,"oh my god, the chicago aquarium closed due to ...",0
67926,67926,1588672910115,209370.0,0,43314,82964,275,NaN,NaN,"COVID19, CoronavirusPandemic",2020-05-05 10:01:50,10,5,5,1,0,0.003315,1,0,0,0,0,2,0,25490.0,0,NaN,NaN,0,0,0,0,0,0,0,0,16,Sicily has figured out this whole self-isolati...,0
416321,416321,1588653801086,208844.0,0,114324,1536,408,NaN,NaN,NaN,2020-05-05 04:43:21,4,5,5,1,0,0.265625,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,15,the government be like: due to the coronavirus...,0
419323,419323,1588711235137,208130.0,0,1091,2487,286,NaN,NaN,NaN,2020-05-05 20:40:35,20,5,5,1,0,0.114998,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,11,COVID-19 helping people realise that some meet...,0
288191,288191,1588678495826,207384.0,0,229097,4344,882,NaN,NaN,NaN,2020-05-05 11:34:55,11,5,5,1,0,0.203039,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,18,Not enough praise has gone to medical professi...,0
618560,618560,1588659206678,204522.0,0,9987,9837,428,NaN,NaN,NaN,2020-05-05 06:13:26,6,5,5,1,0,0.043509,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,10,Coronavirus has crossed the line for Italians ...,0
153971,153971,1588655712228,194810.0,1,278,62754,298,MelBrooks,NaN,"coronavirus, DontBeASpreader",2020-05-05 05:15:12,5,5,5,1,0,0.004749,1,1,0,0,1,2,0,7706.0,0,0.0,0.0,0,0,0,0,0,0,0,0,18,"A message from me and my dad, @Melbrooks. \n\n...",0
197725,197725,1588679567664,187101.0,0,9436,4880,848,NaN,NaN,NaN,2020-05-05 11:52:47,11,5,5,1,0,0.173770,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,29,For the average American the best way to tell ...,0
61201,61201,1588690552467,186897.0,0,22779,681,324,NaN,NaN,NaN,2020-05-05 14:55:52,14,5,5,1,0,0.475771,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,17,My mans House would pop 6 Vicodin on Thursday ...,0
408817,408817,1588663290885,185406.0,0,86803,1238,99,NaN,NaN,NaN,2020-05-05 07:21:30,7,5,5,1,0,0.079968,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,15,when the coronavirus tweets are funny but ur s...,0
470317,470317,1588700599996,178111.0,0,876,5361,4292,NaN,NaN,NaN,2020-05-05 17:43:19,17,5,5,1,0,0.800597,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,20,My dog after I sent him to get supplies since ...,0
535135,535135,1588647965163,168249.0,1,142957,138422,11082,NaN,NaN,NaN,2020-05-05 03:06:05,3,5,5,1,0,0.080060,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,2,0,26,In retrospect Sandy Hook marked the end of the...,0
469058,469058,1588630157117,166665.0,1,15794,117029367,606826,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 22:09:17,22,4,5,0,0,0.005185,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,1,0,0,0,2,1,59,If you’re wondering whether it’s an overreacti...,0
210249,210249,1588615454048,163910.0,0,21633,18035,2849,NaN,NaN,NaN,2020-05-04 18:04:14,18,4,5,0,0,0.157971,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,23,This poor man is going to die tryna save Ameri...,0
277334,277334,1588566245397,160631.0,0,14078,357,225,NaN,NaN,NaN,2020-05-04 04:24:05,4,4,5,0,0,0.630252,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,5,The coronavirus canceling my plans,0
224651,224651,1588698802271,160229.0,0,23928,711,201,NaN,NaN,NaN,2020-05-05 17:13:22,17,5,5,1,0,0.282700,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,17,Me sending my dog out for supplies since he ca...,0
471393,471393,1588682482427,159168.0,0,37875,48801,35254,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 12:41:22,12,5,5,1,0,0.722403,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,27,900 people get Coronavirus and the whole world...,0
340499,340499,1588683476491,156817.0,1,25238,118691,1860,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 12:57:56,12,5,5,1,0,0.015671,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,60,So society’s *real* key workers have just bee...,0
327965,327965,1588709078019,155376.0,1,15802,39492,228,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 20:04:38,20,5,5,1,0,0.005773,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,2,0,57,I see a lot of people being like “I would surv...,0
60577,60577,1588662916620,153743.0,0,13419,1251,762,NaN,NaN,NaN,2020-05-05 07:15:16,7,5,5,1,0,0.609113,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,11,No offense but the corona virus disappearing b...,0
119322,119322,1588648970140,146077.0,0,2548,4109,435,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 03:22:50,3,5,5,1,0,0.105865,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,1,0,0,61,key takeaway: humans aren’t the problem—it’s o...,0
566837,566837,1588677191804,145836.0,1,1243,453844,102,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 11:13:11,11,5,5,1,0,0.000225,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,1,2,1,58,I did the math: a full battery of coronavirus ...,0
495234,495234,1588693071066,144887.0,0,40,32692,0,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 15:37:51,15,5,5,1,0,0.000000,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,14,😀😀😀😀😀😀😀😀😀😀 😀😀😀😀😀😀😀😀😀😀 😀😀😀😀😀😀😀😀pain😀😀 😀😀😀😀😀😀😀😀😀...,0
638579,638579,1588648642050,144605.0,0,328955,2286,1328,NaN,NaN,NaN,2020-05-05 03:17:22,3,5,5,1,0,0.580927,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,6,This is HARD AS FUCK.,0
280864,280864,1588607509243,141000.0,0,800,227,99,NaN,NaN,NaN,2020-05-04 15:51:49,15,4,5,0,0,0.436123,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,13,Imagine you want to sleep at night but your ne...,0
605256,605256,1588573440305,140896.0,0,18364,13605,766,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 06:24:00,6,4,5,0,0,0.056303,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,1,0,1,1,38,fun fact: its tradition for europeans to sprea...,0
430033,430033,1588715000662,138668.0,1,36629,238608,2516,NaN,NaN,NaN,2020-05-05 21:43:20,21,5,5,1,0,0.010544,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,6,How to medical https://t.co/0EDqJcy38p,0
157462,157462,1588321774642,138475.0,0,23905,1086,804,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 08:29:34,8,1,5,4,0,0.740331,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,26,Really don't wanna fucking hear about how hard...,0
60523,60523,1588658214548,138127.0,1,5548,34333517,1953,NaN,NaN,NaN,2020-05-05 05:56:54,5,5,5,1,0,0.000057,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,6,I had gloves on all day..,0
35507,35507,1588333516887,136876.0,0,102923,5444,1484,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 11:45:16,11,1,5,4,0,0.272594,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,1,1,1,1,53,Coronavirus is everywhere. BOOK THAT FLIGHT. T...,0
334253,334253,1588666513951,136665.0,0,4771,440,472,NaN,NaN,NaN,2020-05-05 08:15:13,8,5,5,1,0,1.072727,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,14,"First the coronavirus, \nand now this??\nJesus...",0
331773,331773,1588603693636,133198.0,1,67047,146318,5310,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 14:48:13,14,4,5,0,0,0.036291,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,1,1,0,0,0,2,1,59,If ONE white woman accused me of rape my caree...,0
596182,596182,1588691490352,131810.0,0,841,1851,545,NaN,NaN,NaN,2020-05-05 15:11:30,15,5,5,1,0,0.294435,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,12,So my possum living in the grill had babies ht...,0
459603,459603,1588510433609,131089.0,0,5881,179797,653,NaN,twitter.com/i/web/status/1…,NaN,2020-05-03 12:53:53,12,3,5,6,1,0.003632,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,32,After noticing that Ken slept with a photo of ...,0
465299,465299,1588555957161,131037.0,1,36762,207617,1958,NaN,NaN,NaN,2020-05-04 01:32:37,1,4,5,0,0,0.009431,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,25,Some dude just called me a pussy for putting o...,0
417192,417192,1588701971468,130964.0,1,15795,117057995,606799,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 18:06:11,18,5,5,1,0,0.005184,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,4,0,55,Protect yourself and your community from coron...,0
50242,50242,1588673332425,129528.0,0,22756,25900,3978,NaN,NaN,NaN,2020-05-05 10:08:52,10,5,5,1,0,0.153591,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,8,Coronavirus said this ones for you Princess Diana,0
401441,401441,1588651774289,128469.0,0,5787,3069,267,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 04:09:34,4,5,5,1,0,0.086999,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,60,Yesterday I knocked on my Tennant's door and t...,0
321606,321606,1588702466133,128138.0,0,51319,1313,2095,NaN,NaN,NaN,2020-05-05 18:14:26,18,5,5,1,0,1.595583,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,12,Hockey has been cancelled for like six hours a...,0
592212,592212,1588299085941,126414.0,0,111663,27127,1334,NaN,twitter.com/i/web/status/1…,NaN,2020-05-01 02:11:25,2,1,5,4,0,0.049176,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,2,53,This is the face of someone who just spent 9 h...,0
486991,486991,1588594181612,126026.0,0,6083,591,1005,NaN,NaN,NaN,2020-05-04 12:09:41,12,4,5,0,0,1.700508,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,10,If you believe the world will overcome covid-1...,0
290272,290272,1588557287222,124257.0,1,7081,4589670,808,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 01:54:47,1,4,5,0,0,0.000176,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,69,stop scrolling 🛑 ✋🏾!!! IM FROM THE FUTURE 🤖 🚀🚨...,0
477458,477458,1588681771016,123334.0,1,17932,11918035,1460,NaN,NaN,NaN,2020-05-05 12:29:31,12,5,5,1,0,0.000123,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,13,"Once a vaccine for coronavirus is developed, i...",0
5750,5750,1588665075225,122475.0,0,49182,2149,1635,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 07:51:15,7,5,5,1,0,0.760819,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,43,Can y’all please just follow the government in...,0
568007,568007,1588648779854,122382.0,0,1196,8645,122,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 03:19:39,3,5,5,1,0,0.014112,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,1,0,0,1,54,"I live in Seattle, I have all symptoms of COVI...",0
231642,231642,1588683849841,121405.0,0,65595,6488,634,NaN,NaN,NaN,2020-05-05 13:04:09,13,5,5,1,0,0.097719,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,7,Damn I gotta warn my mum,0
30557,30557,1588640100811,120903.0,0,35482,21398,762,NaN,NaN,NaN,2020-05-05 00:55:00,0,5,5,1,0,0.035611,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,13,coronavirus seeing all the other terrible shit...,0
535541,535541,1588628223199,120632.0,0,102343,2912,1509,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 21:37:03,21,4,5,0,0,0.518201,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,3,0,53,"After COVID-19 is over, I better NEVER hear an...",0
86760,86760,1588584268047,119447.0,0,81119,80412,34025,NaN,NaN,NaN,2020-05-04 09:24:28,9,4,5,0,0,0.423133,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,8,the coronavirus outbreak in Italy https://t.co...,0
436384,436384,1588701292780,118635.0,0,8618,4317,2163,NaN,NaN,NaN,2020-05-05 17:54:52,17,5,5,1,0,0.501042,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,10,Me and my best friend reuniting once coronavir...,0
579912,579912,1588305576565,118362.0,0,4096,19690,7380,NaN,NaN,NaN,2020-05-01 03:59:36,3,1,5,4,0,0.374810,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,14,i can't believe school used to start at 8am an...,0
492090,492090,1588576328356,117236.0,1,8009,80112,1001,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 07:12:08,7,4,5,0,0,0.012495,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,0,0,0,0,48,Italy has banned weddings and funerals for 16 ...,0
602427,602427,1588553259700,116628.0,0,48822,123612,804,NaN,NaN,NaN,2020-05-04 00:47:39,0,4,5,0,0,0.006504,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,12,This is the most Florida tweet I’ve ever seen.,0
191288,191288,1588566767120,116205.0,0,169384,3240,2916,NaN,NaN,NaN,2020-05-04 04:32:47,4,4,5,0,0,0.900000,0,0,0,0,0,0,0,0.0,0,NaN,NaN,1,0,0,0,0,0,0,1,15,“Avoid being in large masses of people to avoi...,0
596549,596549,1588668294650,115846.0,1,14318,454065,27,NaN,NaN,NaN,2020-05-05 08:44:54,8,5,5,1,0,0.000059,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,15,Coronavirus will end soon. In Jesus name. \n\n...,0
485026,485026,1588681705194,114634.0,0,133012,2530,1509,NaN,NaN,NaN,2020-05-05 12:28:25,12,5,5,1,0,0.596443,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,14,LMFAOO They jogging out that bitch like it’s a...,0
228400,228400,1588701470809,112474.0,1,944,100236,5029,NaN,NaN,NaN,2020-05-05 17:57:50,17,5,5,1,0,0.050172,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,27,"A Saudi doctor returns home from the hospital,...",0
498713,498713,1588520325180,108967.0,0,53001,2378,1482,NaN,NaN,NaN,2020-05-03 15:38:45,15,3,5,6,1,0.623213,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,8,Meredith Grey. Ugh this woman is amazing,0
394091,394091,1588650987302,108524.0,0,4397,560,528,NaN,NaN,NaN,2020-05-05 03:56:27,3,5,5,1,0,0.942857,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,16,coronavirus this coronavirus that.... can we t...,0
441362,441362,1588631518294,108010.0,0,16969,2723,541,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 22:31:58,22,4,5,0,0,0.198678,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,2,0,61,"For those of you who don’t know, Cuba’s larges...",0
31017,31017,1588571865928,107476.0,0,39591,9601,798,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 05:57:45,5,4,5,0,0,0.083116,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,0,0,0,0,45,The media: “CORONAVIRUS PANDEMIC IS GETTING WO...,0
503392,503392,1588662061470,106792.0,0,17402,2757,430,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 07:01:01,7,5,5,1,0,0.155967,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,56,seeing alot of people (esp influencers) shamin...,0
86180,86180,1588679783443,105762.0,0,1337,685,133,NaN,NaN,NaN,2020-05-05 11:56:23,11,5,5,1,0,0.194161,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,20,BREAKING NEWS: Due to the recent COVID-19 outb...,0
252655,252655,1588320236485,105598.0,0,755,1880754,0,NaN,NaN,NaN,2020-05-01 08:03:56,8,1,5,4,0,0.000000,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,3,https://t.co/WxJFzvHja4,0
637425,637425,1588631281698,104808.0,0,22519,96401,7650,NaN,NaN,NaN,2020-05-04 22:28:01,22,4,5,0,0,0.079356,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,11,Listen what this doctor said about coronavirus...,0
660972,660972,1588683772420,104696.0,0,16397,31574,1550,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 13:02:52,13,5,5,1,0,0.049091,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,1,0,0,50,This is Generation Z. \n\nI want to name that ...,0
556503,556503,1588635631722,104415.0,0,27752,5911,1841,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 23:40:31,23,4,5,0,0,0.311453,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,0,0,1,0,33,Quote of the year: “If you expect elementary s...,0
497681,497681,1588680268785,104005.0,1,80332,695875,12340,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 12:04:28,12,5,5,1,0,0.017733,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,32,Sandra the orangutang started washing her hand...,0
561557,561557,1588651601322,103708.0,1,8497,3046999,1051,TeamPulte,twitter.com/i/web/status/1…,NaN,2020-05-05 04:06:41,4,5,5,1,0,0.000345,0,1,1,1,1,0,242936,0.0,2,0.0,0.0,0,0,0,0,0,0,0,0,36,I'm going give $300 TODAY to someone random wh...,0
428949,428949,1588288237192,103062.0,1,9503,29142493,126,NaN,NaN,NaN,2020-04-30 23:10:37,23,30,4,3,0,0.000004,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,16,they act like i’m not in full control of where...,0
303209,303209,1588467545279,102674.0,0,1144,2392,222,NaN,twitter.com/i/web/status/1…,NaN,2020-05-03 00:59:05,0,3,5,6,1,0.092809,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,38,"Two nurses, who have witnessed first hand the ...",0
115891,115891,1588678639723,102239.0,0,11738,7661,982,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 11:37:19,11,5,5,1,0,0.128182,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,44,"Husband just told me, “watching the federal go...",0
313705,313705,1588547912685,102037.0,1,17855,444446,5933,NaN,twitter.com/i/web/status/1…,NaN,2020-05-03 23:18:32,23,3,5,6,1,0.013349,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,1,0,0,0,3,58,The H1N1 swine flu pandemic that infected up t...,0
228319,228319,1588555533327,101952.0,0,3190,611,712,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 01:25:33,1,4,5,0,0,1.165303,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,56,The Office: Coronavirus \n\nMichael ignores th...,0
45699,45699,1588480220630,100657.0,0,12380,4757,1074,NaN,NaN,NaN,2020-05-03 04:30:20,4,3,5,6,1,0.225773,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,12,niggas saw that hockey could get canceled and ...,0
91091,91091,1588649957007,100614.0,0,3224,7311,274,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 03:39:17,3,5,5,1,0,0.037478,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,0,0,0,2,68,"So, the last week I have been battling COVID-1...",0
42435,42435,1588689962719,98677.0,0,2404,485,181,NaN,NaN,NaN,2020-05-05 14:46:02,14,5,5,1,0,0.373196,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,14,why coronavirus gotta hit right when i started...,0
638407,638407,1588652589920,98517.0,0,12156,872,525,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 04:23:09,4,5,5,1,0,0.602064,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,26,2004- SARS \n2008- AVIAN \n2010- SWINE \n2014-...,0
54282,54282,1588689993810,97955.0,1,3308,50298361,218,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 14:46:33,14,5,5,1,0,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,50,Halting funding for the World Health Organizat...,0
494987,494987,1588636177403,97924.0,0,52567,46512,10339,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 23:49:37,23,4,5,0,0,0.222287,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,37,"Hi. \n\nYes, it originated in China, but the t...",0
419270,419270,1588573961668,97666.0,0,25581,9679,1595,NaN,NaN,NaN,2020-05-04 06:32:41,6,4,5,0,0,0.164790,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,16,Celebrities keep trying to sing the virus away...,0
406543,406543,1588685303449,97572.0,1,9466,206476,3721,NaN,twitter.com/i/web/status/1…,Coronavirus,2020-05-05 13:28:23,13,5,5,1,0,0.018021,1,0,1,1,0,1,242936,2740.0,0,NaN,NaN,0,0,0,0,0,0,0,0,32,This morning a White House official referred t...,0
404946,404946,1588614765260,97558.0,0,4504,90437,639,NaN,twitter.com/Corona_Bot__/s…,NaN,2020-05-04 17:52:45,17,4,5,0,0,0.007066,0,0,1,1,0,0,4,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,4,WHAT https://t.co/1Qq5x38onc,0
319293,319293,1588609427860,96922.0,1,6813,27868,520,NaN,NaN,NaN,2020-05-04 16:23:47,16,4,5,0,0,0.018659,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,8,Every Friday at exactly 7:30pm https://t.co/71...,0
448498,448498,1588567832167,96409.0,0,210088,43566,35151,NaN,NaN,NaN,2020-05-04 04:50:32,4,4,5,0,0,0.806845,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,10,This is exactly how females are lmfaoooo https...,0
34401,34401,1588641849117,96347.0,0,3028,31568,8243,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 01:24:09,1,5,5,1,0,0.261119,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,1,54,We can now read the Imperial College report on...,0

In [78]:
df.loc[((df["user_statuses_count"] >= 15000) & (df["user_statuses_count"] <= 16000) &
    (df["user_friends_count"] >= 60000) & (df["user_friends_count"] <= 700000)
    & (df["user_followers_count"] >= 2000000))]

,id,timestamp,retweet_count,user_verified,user_statuses_count,user_followers_count,user_friends_count,user_mentions,urls,hashtags,date,hour,day,month,weekday,weekend,friends_followers_ratio,has_hashtags,has_mentions,has_urls,number_of_urls,number_of_mentions,number_of_hashtags,urls_popularity,hashtags_popularity,mentions_popularity,mentions_max_followers,mentions_max_friends,fear,anger,joy,disgust,sadness,surprise,positive,negative,text_size,text,user
36710,36710,1588691847949,39569.0,1,15795,117049250,606800,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 15:17:27,15,5,5,1,0,0.005184,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,1,39,While we continue to wait for a coherent natio...,0
40881,40881,1588702286963,6461.0,1,15795,117058259,606799,"rgay, SheaSerrano",twitter.com/i/web/status/1…,NaN,2020-05-05 18:11:26,18,5,5,1,0,0.005184,0,1,1,1,2,0,242936,0.0,1,0.0,2055.0,0,0,0,0,0,0,1,0,29,.@rgay and @SheaSerrano are using their feeds ...,0
81059,81059,1588702322952,93528.0,1,15795,117058323,606799,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 18:12:02,18,5,5,1,0,0.005184,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,1,0,0,0,0,0,2,0,56,We owe a profound debt of gratitude to all our...,0
223370,223370,1588641154414,10364.0,1,15794,117029017,606821,FoodDepository,twitter.com/i/web/status/1…,NaN,2020-05-05 01:12:34,1,5,5,1,0,0.005185,0,1,1,1,1,0,242936,0.0,1,0.0,1291.0,0,0,0,0,0,0,2,0,50,The folks of the Chicago @fooddepository—and f...,0
241246,241246,1588702306684,37942.0,1,15795,117058583,606797,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 18:11:46,18,5,5,1,0,0.005184,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,1,0,0,0,0,0,2,47,We can't deny that racial and socioeconomic fa...,0
267046,267046,1588637284954,51858.0,1,15794,117031477,606826,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 00:08:04,0,5,5,1,0,0.005185,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,1,51,If we want life to approach anything like norm...,0
308445,308445,1588709550016,37549.0,1,15795,117064033,606798,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 20:12:30,20,5,5,1,0,0.005183,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,29,No one should be forced to choose between thei...,0
324571,324571,1588696530079,10923.0,1,15795,117053174,606797,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 16:35:30,16,5,5,1,0,0.005184,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,55,I’ve always loved joining commencements––the c...,0
417192,417192,1588701971468,130964.0,1,15795,117057995,606799,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 18:06:11,18,5,5,1,0,0.005184,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,4,0,55,Protect yourself and your community from coron...,0
469058,469058,1588630157117,166665.0,1,15794,117029367,606826,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 22:09:17,22,4,5,0,0,0.005185,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,1,0,0,0,2,1,59,If you’re wondering whether it’s an overreacti...,0
485631,485631,1588702172282,9971.0,1,15795,117058185,606799,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 18:09:32,18,5,5,1,0,0.005184,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,30,"Everyone should have the right to vote safely,...",0
529350,529350,1588703408686,42851.0,1,15795,117059317,606799,SenWarren,twitter.com/i/web/status/1…,NaN,2020-05-05 18:30:08,18,5,5,1,0,0.005184,0,1,1,1,1,0,242936,0.0,26,6590472.0,491.0,0,0,0,0,0,0,0,0,29,"As she often does, @SenWarren provides a cogen...",0
562049,562049,1588683453155,42531.0,1,15794,117043299,606805,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 12:57:33,12,5,5,1,0,0.005184,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,45,Some good news: states that started social dis...,0
582674,582674,1588565641877,5721.0,1,15794,116985513,606835,cripchick,twitter.com/i/web/status/1…,NaN,2020-05-04 04:14:01,4,4,5,0,0,0.005187,0,1,1,1,1,0,242936,0.0,0,3395.0,0.0,0,0,0,0,0,0,0,0,28,"And @cripchick, a disabled activist, understan...",0
602831,602831,1588629732147,26530.0,1,15794,117029112,606826,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 22:02:12,22,4,5,0,0,0.005185,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,43,As communities have begun to recognize the imp...,0
611046,611046,1588663907201,51411.0,1,15794,117032915,606813,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 07:31:47,7,5,5,1,0,0.005185,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,2,1,48,"During this crisis, our grocery store clerks, ...",0
701383,701382,1588673259529,NaN,1,15794,117038101,606811,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 10:07:39,10,5,5,1,0,0.005185,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,17,Democracy depends on an informed citizenry and...,0
723261,723260,1588623804058,NaN,1,15794,117024876,606825,NaN,NaN,NaN,2020-05-04 20:23:24,20,4,5,0,0,0.005185,0,0,0,0,0,0,0,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,13,No one is born hating another person because o...,0
725553,725552,1588702244929,NaN,1,15795,117058242,606799,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 18:10:44,18,5,5,1,0,0.005184,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,30,And this article provides a great example of t...,0
765581,765580,1588674087683,NaN,1,15794,117038531,606811,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 10:21:27,10,5,5,1,0,0.005185,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,2,Mayors have been working hard to help us get t...,0
831433,831432,1588702253187,NaN,1,15795,117058253,606799,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 18:10:53,18,5,5,1,0,0.005184,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,8,Here’s a useful summary of the current best th...,0
847426,847425,1588702249595,NaN,1,15795,117058239,606799,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 18:10:49,18,5,5,1,0,0.005184,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,8,Our medical professionals are heroes putting t...,0
869628,869627,1588572672517,NaN,1,15794,116990975,606831,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 06:11:12,6,4,5,0,0,0.005187,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,7,"A shout out to Kevin, Giannis, Zion, Blake, St...",0
881346,881345,1588713903067,NaN,1,15795,117066119,606788,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 21:25:03,21,5,5,1,0,0.005183,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,25,Here’s a useful overview of the likely scenari...,0
925215,925214,1588647963833,NaN,1,15794,117024709,606819,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 03:06:03,3,5,5,1,0,0.005185,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,15,Social distancing bends the curve and relieves...,0
935436,935435,1588638983603,NaN,1,15794,117032441,606826,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 00:36:23,0,5,5,1,0,0.005185,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,1,42,The pandemic has magnified the financial insec...,0

In [79]:
df.loc[((df["user_statuses_count"] >= 15000) & (df["user_statuses_count"] <= 16000) &
    (df["user_friends_count"] >= 60000) & (df["user_friends_count"] <= 700000)
    & (df["user_followers_count"] >= 2000000)), "user"] = "Obama"

In [86]:
df.nlargest(100, ["retweet_count"]).loc[df.nlargest(100, ["retweet_count"])["user"] == '0']

TypeError: ignored

In [82]:
df.loc[((df["user_statuses_count"] >= 2900) & (df["user_statuses_count"] <= 3500) &
    (df["user_friends_count"] >= 210) & (df["user_friends_count"] <= 230)
    & (df["user_followers_count"] >= 50000000))]

,id,timestamp,retweet_count,user_verified,user_statuses_count,user_followers_count,user_friends_count,user_mentions,urls,hashtags,date,hour,day,month,weekday,weekend,friends_followers_ratio,has_hashtags,has_mentions,has_urls,number_of_urls,number_of_mentions,number_of_hashtags,urls_popularity,hashtags_popularity,mentions_popularity,mentions_max_followers,mentions_max_friends,fear,anger,joy,disgust,sadness,surprise,positive,negative,text_size,text,user
9741,9741,1588674838156,7092.0,1,3308,50293176,218,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 10:33:58,10,5,5,1,0,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,2,0,52,Humankind has never had a more urgent task tha...,0
12994,12994,1588532060312,1497.0,1,3307,50259622,217,"CEPIvaccines, gavi",twitter.com/i/web/status/1…,NaN,2020-05-03 18:54:20,18,3,5,6,1,0.000004,0,1,1,1,2,0,242936,0.0,15,129013.0,1355.0,0,0,0,0,0,0,2,0,33,The international response will require fundin...,0
44671,44671,1588709847018,1472.0,1,3309,50305763,218,NickKristof,twitter.com/i/web/status/1…,NaN,2020-05-05 20:17:27,20,5,5,1,0,0.000004,0,1,1,1,1,0,242936,0.0,12,2049029.0,2661.0,1,0,0,0,0,0,1,0,27,.@NickKristof does an amazing job capturing th...,0
54282,54282,1588689993810,97955.0,1,3308,50298361,218,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 14:46:33,14,5,5,1,0,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,1,50,Halting funding for the World Health Organizat...,0
114336,114336,1588531965563,4304.0,1,3307,50259600,217,NaN,twitter.com/i/web/status/1…,NaN,2020-05-03 18:52:45,18,3,5,6,1,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,2,0,46,We don’t yet have all the tools we need to fig...,0
193669,193669,1588663235674,2124.0,1,3308,50290526,218,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 07:20:35,7,5,5,1,0,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,42,There are few people I’ve learned more from ov...,0
220804,220804,1588702736677,2024.0,1,3309,50303497,218,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 18:18:56,18,5,5,1,0,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,1,0,26,It’s encouraging to see the first projects beg...,0
250975,250975,1588532057357,499.0,1,3307,50259622,217,allinseattle,twitter.com/i/web/status/1…,COVID19,2020-05-03 18:54:17,18,3,5,6,1,0.000004,1,1,1,1,1,1,242936,25490.0,0,0.0,0.0,0,0,0,0,0,0,1,0,50,Lots of people in Seattle have asked how they ...,0
360553,360553,1588531999704,1263.0,1,3307,50259611,217,"TEDchris, WhitPennRod",twitter.com/i/web/status/1…,NaN,2020-05-03 18:53:19,18,3,5,6,1,0.000004,0,1,1,1,2,0,242936,0.0,1,0.0,0.0,0,0,0,0,0,0,1,0,31,I’m connecting live with @TEDchris and @WhitPe...,0
404803,404803,1588693907940,1586.0,1,3308,50300118,218,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 15:51:47,15,5,5,1,0,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,45,If we make the right decisions now—informed by...,0
441598,441598,1588713313370,782.0,1,3309,50306485,218,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 21:15:13,21,5,5,1,0,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,33,"Class of 2020, these are not easy times. But w...",0
543278,543278,1588650228633,4446.0,1,3308,50284687,218,NaN,twitter.com/i/web/status/1…,NaN,2020-05-05 03:43:48,3,5,5,1,0,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,31,We don't yet have all the tools we need to sto...,0
650945,650945,1588532004102,1322.0,1,3307,50259611,217,NaN,twitter.com/i/web/status/1…,NaN,2020-05-03 18:53:24,18,3,5,6,1,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,4,0,54,Teachers are doing incredible work to keep kid...,0
724431,724430,1588587490880,NaN,1,3307,50271607,217,IHME_UW,twitter.com/i/web/status/1…,NaN,2020-05-04 10:18:10,10,4,5,0,0,0.000004,0,1,1,1,1,0,242936,0.0,10,53461.0,2886.0,0,0,0,0,0,0,0,0,14,This impressive new tool from @IHME_UW will he...,0
741761,741760,1588611013021,NaN,1,3307,50280706,217,NaN,twitter.com/i/web/status/1…,COVID19,2020-05-04 16:50:13,16,4,5,0,0,0.000004,1,0,1,1,0,1,242936,25490.0,0,NaN,NaN,0,0,0,0,0,0,0,0,48,One of the questions I am most often asked abo...,0
751865,751864,1588693956376,NaN,1,3308,50300150,218,NaN,twitter.com/i/web/status/1…,coronavirus,2020-05-05 15:52:36,15,5,5,1,0,0.000004,1,0,1,1,0,1,242936,7706.0,0,NaN,NaN,0,0,0,0,0,0,0,0,3,There’s no question the United States missed t...,0
766422,766421,1588531996427,NaN,1,3307,50259610,217,reddit,twitter.com/i/web/status/1…,COVID19,2020-05-03 18:53:16,18,3,5,6,1,0.000004,1,1,1,1,1,1,242936,25490.0,4,0.0,0.0,0,0,0,0,0,1,3,0,49,Thanks @reddit for joining me yesterday to dis...,0
818685,818684,1588532083610,NaN,1,3307,50259635,217,NaN,twitter.com/i/web/status/1…,NaN,2020-05-03 18:54:43,18,3,5,6,1,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,3,"This is encouraging news, but we still have a ...",0
828851,828850,1588590395847,NaN,1,3307,50272748,217,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 11:06:35,11,4,5,0,0,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,20,What’s next for our foundation? I’m particular...,0
840588,840587,1588613237200,NaN,1,3307,50281642,217,NaN,twitter.com/i/web/status/1…,NaN,2020-05-04 17:27:17,17,4,5,0,0,0.000004,0,0,1,1,0,0,242936,0.0,0,NaN,NaN,0,0,0,0,0,0,0,0,16,COVID-19 could be a once-in-a-century pandemic...,0
871277,871276,1588613199669,NaN,1,3307,50281617,217,reddit,b-gat.es/2xJYgp3,COVID19,2020-05-04 17:26:39,17,4,5,0,0,0.000004,1,1,1,1,1,1,0,25490.0,4,0.0,0.0,0,0,0,0,0,0,0,0,50,I’m answering your questions about the #COVID1...,0

In [83]:
df.loc[((df["user_statuses_count"] >= 2900) & (df["user_statuses_count"] <= 3500) &
    (df["user_friends_count"] >= 210) & (df["user_friends_count"] <= 230)
    & (df["user_followers_count"] >= 50000000))] = "Bill_Gates"

In [85]:
df.nlargest(100, ["retweet_count"]).loc[df.nlargest(100, ["retweet_count"])["user"] == '0']

TypeError: ignored